In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\warden\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\warden\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\warden\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.




A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\warden\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\warden\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\warden\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.




A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\warden\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\warden\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\warden\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\warden\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\warden\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\warden\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



In [3]:
customers_df = pd.read_csv('Customers.csv')
transactions_df = pd.read_csv('Transactions.csv')
products_df = pd.read_csv('Products.csv')

In [9]:
transactions_with_products = transactions_df.merge(products_df, on='ProductID')
merged_data = transactions_with_products.merge(customers_df, on='CustomerID')

print(merged_data.columns)

Index(['TransactionID', 'CustomerID', 'ProductID', 'TransactionDate',
       'Quantity', 'TotalValue', 'Price_x', 'ProductName', 'Category',
       'Price_y', 'CustomerName', 'Region', 'SignupDate'],
      dtype='object')


In [11]:
merged_data.sample(10)

TransactionID CustomerID ProductID      TransactionDate  Quantity  \
729        T00845      C0154      P083  2023-12-31 15:44:04         2   
310        T00033      C0099      P036  2024-12-17 22:52:47         2   
628        T00267      C0037      P066  2024-06-30 00:11:05         3   
379        T00864      C0096      P025  2024-08-22 05:45:56         4   
38         T00105      C0087      P049  2024-02-12 08:14:34         3   
612        T00245      C0120      P089  2024-04-28 20:01:47         4   
878        T00876      C0044      P075  2024-10-22 02:45:04         2   
342        T00667      C0047      P058  2024-04-26 14:16:50         2   
264        T00420      C0057      P086  2024-07-31 21:34:31         4   
505        T00116      C0127      P032  2024-08-15 21:51:12         1   

     TotalValue  Price_x                  ProductName     Category  Price_y  \
729      911.44   455.72        ActiveWear Smartwatch  Electronics   455.72   
310      745.10   372.55             BookWorld Jacket     Clothing   372.55   
628     1011.66   337.22           SoundWave Textbook        Books   337.22   
379     1138.48   284.62      ActiveWear Cookware Set   Home Decor   284.62   
38       443.85   147.95             TechPro Textbook        Books   147.95   
612      883.64   220.91  HomeSense Bluetooth Speaker  Electronics   220.91   
878      995.52   497.76             TechPro Textbook        Books   497.76   
342      315.24   157.62          ActiveWear Textbook        Books   157.62   
264     1762.80   440.70              SoundWave Novel        Books   440.70   
505      488.63   488.63           BookWorld Cookbook        Books   488.63   

          CustomerName         Region  SignupDate  
729       Robert Sharp  North America  2024-10-27  
310       Rodney Eaton  South America  2023-01-29  
628        Linda Smith         Europe  2023-02-04  
379   Benjamin Mcclure  South America  2022-11-18  
38     Travis Campbell  South America  2024-04-11  
612     Francisco Diaz  South America  2023-01-13  
878  Kenneth Alexander         Europe  2024-07-10  
342     Samantha Frank  North America  2024-03-22  
264   Elizabeth Nguyen         Europe  2024-07-27  
505    Kathryn Stevens         Europe  2024-04-04

In [45]:
transactions_with_products = transactions_df.merge(
    products_df.rename(columns={'Price': 'ProductPrice'}), on='ProductID'
)

merged_data = transactions_with_products.merge(customers_df, on='CustomerID')

In [47]:
customer_features = merged_data.groupby('CustomerID').agg(
    total_spending=('TotalValue', 'sum'),
    num_transactions=('TransactionID', 'count'),
    avg_price_per_transaction=('ProductPrice', 'mean'),
    most_common_category=('Category', lambda x: x.mode()[0])
).reset_index()

In [49]:
encoded_customers = customers_df[['CustomerID', 'Region']].merge(customer_features, on='CustomerID')
encoded_customers = pd.get_dummies(encoded_customers, columns=['Region', 'most_common_category'], drop_first=True)

In [51]:
scaler = StandardScaler()
features = scaler.fit_transform(encoded_customers.drop(columns=['CustomerID']))

In [53]:
similarity_matrix = cosine_similarity(features)


In [55]:
customer_ids = encoded_customers['CustomerID'].tolist()
lookalike_map = {}

In [69]:
for i, customer_id in enumerate(customer_ids[:20]):  # First 20 customers
    similar_indices = similarity_matrix[i].argsort()[::-1][1:4]  # Top 3 most similar (exclude self)
    lookalikes = [(customer_ids[j], float(similarity_matrix[i][j])) for j in similar_indices]
    lookalike_map[customer_id] = lookalikes

In [77]:
lookalike_df = pd.DataFrame({
    'CustomerID': lookalike_map.keys(),
    'Lookalikes': [str(lookalikes) for lookalikes in lookalike_map.values()]
})
lookalike_df.to_csv('Swarnendu_Banik_Lookalike.csv', index=False)

In [75]:
print(similarity_matrix[:5, :5])

[[ 1.         -0.30649831  0.15544862  0.35029847  0.54528187]
 [-0.30649831  1.         -0.06499741 -0.28086613  0.02781895]
 [ 0.15544862 -0.06499741  1.          0.25761132 -0.21325526]
 [ 0.35029847 -0.28086613  0.25761132  1.         -0.44191053]
 [ 0.54528187  0.02781895 -0.21325526 -0.44191053  1.        ]]


In [79]:
print(lookalike_df.head())

  CustomerID                                         Lookalikes
0      C0001  [('C0181', 0.9829643469753961), ('C0192', 0.95...
1      C0002  [('C0088', 0.9764068890164818), ('C0134', 0.94...
2      C0003  [('C0025', 0.9804399773534254), ('C0031', 0.97...
3      C0004  [('C0165', 0.970907661586851), ('C0153', 0.921...
4      C0005  [('C0186', 0.9884948596671941), ('C0140', 0.98...
